rtl8821ce: fix build with kernel 6.3
Change due to commit b8c9024e0 "wifi: cfg80211: Add link_id to cfg80211_ch_switch_started_notify()"

Fixes the followin building error:

./out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:421:55: error: too few arg
uments to function call, expected 4, have 3
        cfg80211_ch_switch_notify(adapter->pnetdev, &chdef, 0);
        ~~~~~~~~~~~~~~~~~~~~~~~~~                            ^
/home/utente/r-x86_kernel/kernel/include/net/cfg80211.h:8375:6: note: 'cfg80211_ch_switch_notify' declared here
void cfg80211_ch_switch_notify(struct net_device *dev,
     ^
1 error generated.