rtl8821ce: fix build with kernel 6.13
Changes due to commit 9c4f830 "wifi: cfg80211: pass net_device to .set_monitor_channel"

Fixes the following building error:

./out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9673:25:
error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, struct cfg80211_chan_def *)'
with an expression of type 'int (struct wiphy *, struct cfg80211_chan_def *)' [-Werror,-Wincompatible-function-pointer-types]
        .set_monitor_channel = cfg80211_rtw_set_monitor_channel,
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.