rtl8821ce: fix build with kernel 6.1
Changes due to the following commits:

de492c83cae "prandom: remove unused functions"
b48b89f9c18 "net: drop the weight argument from netif_napi_add"
e7a7b84e331 "wifi: cfg80211: Add link_id parameter to various key operations for MLO"

Fixes the following building errors:

/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/osdep_service.c:2650:9: error: implicit dec
laration of function 'prandom_u32' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        return prandom_u32();
               ^
1 error generated.

/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/os_intfs.c:1683:59: error: too many argument
s to function call, expected 3, have 4
        netif_napi_add(ndev, &adapter->napi, rtw_recv_napi_poll, RTL_NAPI_WEIGHT);
        ~~~~~~~~~~~~~~                                           ^~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8821ce/include/rtw_recv.h:54:27: note: expanded from macro 'RTL_
NAPI_WEIGHT'
                #define RTL_NAPI_WEIGHT (32)
                                        ^~~~
/home/utente/r-x86_kernel/kernel/include/linux/netdevice.h:2562:1: note: 'netif_napi_add' declared here
netif_napi_add(struct net_device *dev, struct napi_struct *napi,
^
1 error generated.

/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9570:13: error: incomp
atible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *, struct key
_params *)' (aka 'int (*)(struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *, struct key_pa
rams *)') with an expression of type 'int (struct wiphy *, struct net_device *, u8, bool, const u8 *, struct key_params *)' (a
ka 'int (struct wiphy *, struct net_device *, unsigned char, _Bool, const unsigned char *, struct key_params *)') [-Werror,-Wi
ncompatible-function-pointer-types]
        .add_key = cfg80211_rtw_add_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9571:13: error: incomp
atible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *, void *, vo
id (*)(void *, struct key_params *))' (aka 'int (*)(struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsi
gned char *, void *, void (*)(void *, struct key_params *))') with an expression of type 'int (struct wiphy *, struct net_devi
ce *, u8, bool, const u8 *, void *, void (*)(void *, struct key_params *))' (aka 'int (struct wiphy *, struct net_device *, un
signed char, _Bool, const unsigned char *, void *, void (*)(void *, struct key_params *))') [-Werror,-Wincompatible-function-p
ointer-types]
        .get_key = cfg80211_rtw_get_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9572:13: error: incomp
atible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *)' (aka 'int
 (*)(struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *)') with an expression of type 'int
(struct wiphy *, struct net_device *, u8, bool, const u8 *)' (aka 'int (struct wiphy *, struct net_device *, unsigned char, _B
ool, const unsigned char *)') [-Werror,-Wincompatible-function-pointer-types]
        .del_key = cfg80211_rtw_del_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9573:21: error: incomp
atible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, bool)' (aka 'int (*)(s
truct wiphy *, struct net_device *, int, unsigned char, _Bool, _Bool)') with an expression of type 'int (struct wiphy *, struc
t net_device *, u8, bool, bool)' (aka 'int (struct wiphy *, struct net_device *, unsigned char, _Bool, _Bool)') [-Werror,-Winc
ompatible-function-pointer-types]
        .set_default_key = cfg80211_rtw_set_default_key,
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.