rtl8723bu: fix build with kernel 6.8
Changes due to the following commit:
49a78b0 "USB: core: Use device_driver directly in struct usb_driver and usb_device_driver"

Fixes the following building error:

./out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/usb_intf.c:253:10: error: field designator 'drvwrap' does not refer to any field in type 'struct usb_driver'
        .usbdrv.drvwrap.driver.shutdown = rtw_dev_shutdown,
                ^
1 error generated.