rtl8812au: fix build with kernel 6.1
Changes due to the following commit

e7a7b84e331 "wifi: cfg80211: Add link_id parameter to various key operations for MLO"

Fixes the following building errors:

/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8812au/os_dep/ioctl_cfg80211.c:5071:13: error: incompatible func
tion pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *, struct key_params *)' (aka
 'int (*)(struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *, struct key_params *)') with an exp
ression of type 'int (struct wiphy *, struct net_device *, u8, bool, const u8 *, struct key_params *)' (aka 'int (struct wiphy *, s
truct net_device *, unsigned char, _Bool, const unsigned char *, struct key_params *)') [-Werror,-Wincompatible-function-pointer-ty
pes]
        .add_key = cfg80211_rtw_add_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8812au/os_dep/ioctl_cfg80211.c:5072:13: error: incompatible func
tion pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *, void *, void (*)(void *, s
truct key_params *))' (aka 'int (*)(struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *, void *,
void (*)(void *, struct key_params *))') with an expression of type 'int (struct wiphy *, struct net_device *, u8, bool, const u8 *
, void *, void (*)(void *, struct key_params *))' (aka 'int (struct wiphy *, struct net_device *, unsigned char, _Bool, const unsig
ned char *, void *, void (*)(void *, struct key_params *))') [-Werror,-Wincompatible-function-pointer-types]
        .get_key = cfg80211_rtw_get_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8812au/os_dep/ioctl_cfg80211.c:5073:13: error: incompatible func
tion pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *)' (aka 'int (*)(struct wiph
y *, struct net_device *, int, unsigned char, _Bool, const unsigned char *)') with an expression of type 'int (struct wiphy *, stru
ct net_device *, u8, bool, const u8 *)' (aka 'int (struct wiphy *, struct net_device *, unsigned char, _Bool, const unsigned char *
)') [-Werror,-Wincompatible-function-pointer-types]
        .del_key = cfg80211_rtw_del_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8812au/os_dep/ioctl_cfg80211.c:5074:21: error: incompatible func
tion pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, bool)' (aka 'int (*)(struct wiphy *, s
truct net_device *, int, unsigned char, _Bool, _Bool)') with an expression of type 'int (struct wiphy *, struct net_device *, u8, b
ool, bool)' (aka 'int (struct wiphy *, struct net_device *, unsigned char, _Bool, _Bool)') [-Werror,-Wincompatible-function-pointer
-types]
        .set_default_key = cfg80211_rtw_set_default_key,
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.