rtl8723bu: fix build with kernel 6.0
Changes due to following commits:

b327c84c328 "wifi: mac80211: replace link_id with link_conf in start/stop_ap()"
efbabc11650 "cfg80211: Indicate MLO connection info in connect and roam callbacks"
ae7ba17b49b "wifi: mac80211: pass the link id in start/stop ap"
7b0a0e3c3a8 "wifi: cfg80211: do some rework towards MLO link APIs"

Fixes the following building errors:

/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:823:13: error: no member named 'bssid' in 'struct cfg80211_roam_info'
                roam_info.bssid = cur_network->network.MacAddress;
                ~~~~~~~~~ ^
/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:6524:13: error: incompatible pointer types initializing 'int (*)(struct wiphy *, struct net_device *, unsigned int)' with an expression of type 'int (struct wiphy *, struct net_device *)' [-Werror,-Wincompatible-pointer-types]
        .stop_ap = cfg80211_rtw_stop_ap,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:6713:12: error: no member named 'current_bss' in 'struct wireless_dev'
        if (wdev->current_bss) {
            ~~~~  ^
3 errors generated.