rtl8812au: fix build with kernel 6.0
Changes due to following commits:

b327c84c328 "wifi: mac80211: replace link_id with link_conf in start/stop_ap()"		2022-07-15 11:43:17 +0200
efbabc11650 "cfg80211: Indicate MLO connection info in connect and roam callbacks"	2022-06-20 12:57:09 +0200
ae7ba17b49b "wifi: mac80211: pass the link id in start/stop ap"				2022-06-20 12:57:08 +0200
7b0a0e3c3a8 "wifi: cfg80211: do some rework towards MLO link APIs"			2022-06-20 12:54:58 +0200

Fixes the following building errors:

/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8812au/os_dep/ioctl_cfg80211.c:484:13: error: no member named 'channel' in 'struct cfg80211_roam_info'
                roam_info.channel = notify_channel;
                ~~~~~~~~~ ^
/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8812au/os_dep/ioctl_cfg80211.c:485:13: error: no member named 'bssid' in 'struct cfg80211_roam_info'
                roam_info.bssid = cur_network->network.MacAddress;
                ~~~~~~~~~ ^
/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8812au/os_dep/ioctl_cfg80211.c:5091:13: error: incompatible pointer types initializing 'int (*)(struct wiphy *, struct net_device *, unsigned int)' with an expression of type 'int (struct wiphy *, struct net_device *)' [-Werror,-Wincompatible-pointer-types]
        .stop_ap = cfg80211_rtw_stop_ap,
                   ^~~~~~~~~~~~~~~~~~~~
3 errors generated.