wl: fix build with kernel 6.0
Changes due to commit

efbabc11650 "cfg80211: Indicate MLO connection info in connect and roam callbacks"

Fixes the following building errors:

/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/wl/src/wl/sys/wl_cfg80211_hybrid.c:2534:12: error: no member named 'channel' in 'struct cfg80211_roam_info'
        roam_info.channel = &wl->conf->channel;
        ~~~~~~~~~ ^
/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/wl/src/wl/sys/wl_cfg80211_hybrid.c:2535:12: error: no member named 'bssid' in 'struct cfg80211_roam_info'
        roam_info.bssid = (u8*)&wl->bssid;
        ~~~~~~~~~ ^
2 errors generated.