wl: fix build with kernel 6.14
Changes due to kernel commit 24dab555 ("wifi: mac80211: get tx power per link")

Fixes the following building error:

src/wl/sys/wl_cfg80211_hybrid.c:1892:18: error: incompatible function pointer types initializing
'int (*)(struct wiphy *, struct wireless_dev *, unsigned int, int *)' with an expression of type
's32 (struct wiphy *, struct wireless_dev *, s32 *)' (aka 'int (struct wiphy *, struct wireless_dev *, int *)') [-Werror,-Wincompatible-function-pointer-types]
        .get_tx_power = wl_cfg80211_get_tx_power,
                        ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

NOTE: s32 type was kept where possible, but unsigned int type was required for link_id, to avoid the above building error.