rtl8723bu: fix build with kernel 6.1
Changes due to the following commits:

de492c83cae "prandom: remove unused functions"
e7a7b84e331 "wifi: cfg80211: Add link_id parameter to various key operations for MLO"

Fixes the following building errors:

/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/osdep_service.c:2101:9: error: implicit dec
laration of function 'prandom_u32' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        return prandom_u32();
               ^
1 error generated.

/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:6500:13: error: incomp
atible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *, struct key
_params *)' (aka 'int (*)(struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *, struct key_pa
rams *)') with an expression of type 'int (struct wiphy *, struct net_device *, u8, bool, const u8 *, struct key_params *)' (a
ka 'int (struct wiphy *, struct net_device *, unsigned char, _Bool, const unsigned char *, struct key_params *)') [-Werror,-Wi
ncompatible-function-pointer-types]
        .add_key = cfg80211_rtw_add_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:6501:13: error: incomp
atible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *, void *, vo
id (*)(void *, struct key_params *))' (aka 'int (*)(struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsi
gned char *, void *, void (*)(void *, struct key_params *))') with an expression of type 'int (struct wiphy *, struct net_devi
ce *, u8, bool, const u8 *, void *, void (*)(void *, struct key_params *))' (aka 'int (struct wiphy *, struct net_device *, un
signed char, _Bool, const unsigned char *, void *, void (*)(void *, struct key_params *))') [-Werror,-Wincompatible-function-p
ointer-types]
        .get_key = cfg80211_rtw_get_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:6502:13: error: incomp
atible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, const u8 *)' (aka 'int
 (*)(struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *)') with an expression of type 'int
(struct wiphy *, struct net_device *, u8, bool, const u8 *)' (aka 'int (struct wiphy *, struct net_device *, unsigned char, _B
ool, const unsigned char *)') [-Werror,-Wincompatible-function-pointer-types]
        .del_key = cfg80211_rtw_del_key,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:6503:21: error: incomp
atible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, int, u8, bool, bool)' (aka 'int (*)(s
truct wiphy *, struct net_device *, int, unsigned char, _Bool, _Bool)') with an expression of type 'int (struct wiphy *, struc
t net_device *, u8, bool, bool)' (aka 'int (struct wiphy *, struct net_device *, unsigned char, _Bool, _Bool)') [-Werror,-Winc
ompatible-function-pointer-types]
        .set_default_key = cfg80211_rtw_set_default_key,
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.