wl: Fix build with Clang
Patch is added to set EXTRA_CFLAGS := -Wno-error=incompatible-pointer-types

Fixes the following building error:

obj/kmodule/wl/src/wl/sys/wl_linux.c:3383:58:
error: incompatible pointer types passing 'const struct file_operations *' to parameter of type 'const struct proc_ops *'
[-Werror,-Wincompatible-pointer-types]
        if ((wl->proc_entry = proc_create_data(tmp, 0644, NULL, &wl_fops, wl)) == NULL) {
                                                                ^~~~~~~~
/home/utente/r-x86_houdini/kernel/include/linux/proc_fs.h:106:36: note: passing argument to parameter here
                                               const struct proc_ops *,
                                                                      ^
1 error generated.