rtl8723bu: fix build with kernel 6.7
Changes due to the following commits:
bb55441c57c "wifi: cfg80211: split struct cfg80211_ap_settings"
66f85d57b71 "wifi: cfg80211: modify prototype for change_beacon"

Fixes the followin building error:

./out/target/product/x86_64/obj/kmodule/rtl8723bu/os_dep/linux/ioctl_cfg80211.c:6544:19:
error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)' with an expression of type 'int (struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)' [-Werror,-Wincompatible-function-pointer-types]
        .change_beacon = cfg80211_rtw_change_beacon,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.