rtl8821ce: fix build with kernel 6.9
Changes due to the following commit:
b82730b "wifi: cfg80211/mac80211: move puncturing into chandef"

Fixes the following building error:

./out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:421:57: error: too many arguments to functio
n call, expected 3, have 4
        cfg80211_ch_switch_notify(adapter->pnetdev, &chdef, 0, 0);
        ~~~~~~~~~~~~~~~~~~~~~~~~~                              ^
./kernel/include/net/cfg80211.h:8793:6: note: 'cfg80211_ch_switch_notify' declared here
void cfg80211_ch_switch_notify(struct net_device *dev,
     ^
1 error generated.