rtl8821ce: fix build with kernel 6.0
Changes due to following commits:

b327c84c328 "wifi: mac80211: replace link_id with link_conf in start/stop_ap()"
efbabc11650 "cfg80211: Indicate MLO connection info in connect and roam callbacks"
ae7ba17b49b "wifi: mac80211: pass the link id in start/stop ap"
7b0a0e3c3a8 "wifi: cfg80211: do some rework towards MLO link APIs"

Fixes the following building errors:

/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:420:52: error: too few arguments to function call, expected 3, have 2
        cfg80211_ch_switch_notify(adapter->pnetdev, &chdef);
        ~~~~~~~~~~~~~~~~~~~~~~~~~                         ^
/home/utente/q-x86/kernel/include/net/cfg80211.h:8261:1: note: 'cfg80211_ch_switch_notify' declared here
void cfg80211_ch_switch_notify(struct net_device *dev,
^
/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:1079:13: error: no member named 'bssid' in 'struct cfg80211_roam_info'
                roam_info.bssid = cur_network->network.MacAddress;
                ~~~~~~~~~ ^
/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9593:13: error: incompatible pointer types initializing 'int (*)(struct wiphy *, struct net_device *, unsigned int)' with an expression of type 'int (struct wiphy *, struct net_device *)' [-Werror,-Wincompatible-pointer-types]
        .stop_ap = cfg80211_rtw_stop_ap,
                   ^~~~~~~~~~~~~~~~~~~~
/home/utente/q-x86/out/target/product/x86_64/obj/kmodule/rtl8821ce/os_dep/linux/ioctl_cfg80211.c:9862:12: error: no member named 'current_bss' in 'struct wireless_dev'
        if (wdev->current_bss) {
            ~~~~  ^
4 errors generated.